Kubaw/ create products services
IO2-InGreed1/IO2_InGreed.io-1 pull request #22
Opened 2024-04-24 22:43 UTC by Wierzb

2024-04-26 05:06 UTC, zuzwoj approved these changes
Ok byczku

2024-04-26 09:24 UTC, portalion requested changes

2024-04-26 09:24 UTC, portalion commented on Src/InGreed.Api/Controllers/ProductController.cs
> +    public ActionResult<Product> Modify(int productToModifyId, [FromBody] Product product)
Add Contract for request

2024-04-26 09:24 UTC, portalion commented on Src/InGreed.Api/Controllers/ProductController.cs
> +    public ActionResult<Product> Create([FromBody] Product product)
Add Contract for request

2024-04-26 09:24 UTC, portalion commented on Src/InGreed.Api/Controllers/ProductController.cs
> +    public ActionResult<List<Product>> GetAllProducts()
Add Contract for request

2024-04-26 09:24 UTC, portalion commented on Src/InGreed.Api/Controllers/ProductController.cs
> +    public ActionResult<Product> GetById(int id)
Add Contract for request

2024-05-03 20:26 UTC, portalion approved these changes

2024-05-03 20:26 UTC, merged